# Generated by Django 4.2.1 on 2023-05-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
    ]
