# Generated by Django 4.2.1 on 2023-05-20 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0002_alter_rate_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
